// UI တွင်ပြသမည့် စာသားများ (System Dictionary)
const SYS_DICT = {
  my: {
    app_title: "MMK ↔ THB & VND ငွေလဲတွက်ချက်ခြင်း",
    app_sub: "MMK ↔ THB & VND Exchange Calculator",
    rate_thb_100k: "၁ သိန်း အတွက် ဘတ် (THB)",
    rate_thb_sub: "THB per 100,000 MMK",
    rate_mmk_1thb: "၁ ဘတ် အတွက် ကျပ် (MMK)",
    rate_mmk_sub: "MMK per 1 THB",
    rate_vnd_1mmk: "၁ ကျပ် အတွက် ဒေါင် (VND)",
    rate_vnd_sub: "VND per 1 MMK",
    ph_ex1: "ဥပမာ - 820",
    ph_ex2: "ဥပမာ - 121.95",
    ph_ex3: "ဥပမာ - 6.5",
    thb_to_mmk: "ဘတ် → မြန်မာကျပ်",
    mmk_to_thb: "မြန်မာကျပ် → ဘတ်",
    vnd_to_mmk: "ဗီယက်နမ်ဒေါင် → မြန်မာကျပ်",
    mmk_to_vnd: "မြန်မာကျပ် → ဗီယက်နမ်ဒေါင်",
    lbl_thb: "ဘတ်ငွေ",
    lbl_mmk: "မြန်မာကျပ်",
    lbl_vnd: "ဒေါင်ငွေ",
    ph_enter: "ရိုက်ထည့်ပါ",
    btn_png: "Save PNG",
    btn_jpg: "Save JPEG",
    btn_share: "📤 Share",
    btn_copy: "📋 Copy Text",
    export_st_title: "Save PNG/JPEG + Bank QR",
    export_st_sub: "QR / Bank Info / မပါ — တစ်ခုတည်းပဲရွေးနိုင်",
    lbl_save_lang: "Save Export Language",
    lbl_qr_sel: "QR Select",
    lbl_bank_sel: "Bank Select",
    lbl_inc: "Export ထဲ ဘာထည့်မလဲ",
    rad_none: "မပါ (Default)",
    rad_qr: "QR ပဲပါ",
    rad_bank: "Bank Info ပဲပါ",
    lbl_cus: "👥 Customer (မရွေးပါက ပြေစာတွင်မပါပါ)",
    btn_quick_add: "➕ အမြန်ထည့်မည်",
    preview: "Preview",
    owner_name: "အကောင့်နာမည်: ",
    bank_preview: "Bank Info Preview",
    
    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— QR ရွေးပါ —",
    ph_bank_sel: "— ဘဏ်ရွေးပါ —",
    ph_cus_sel: "— မထည့်ပါ —",

    // Admin Panel — Main Button / Modal Title
    btn_admin_open: "🔒 Admin / Staff",
    admin_title: "⚙️ Admin ဆက်တင်များ",
    btn_manual_lot: "➕ Manual Lot ထည့်ရန်",
    btn_pdf_report: "📄 PDF စာရင်းချုပ်",
    btn_role_main_admin: "⚙️ Main Admin",
    btn_role_admin: "🛡️ Admin",
    btn_role_staff: "📜 Staff",
    admin_title_main_admin: "⚙️ Main Admin ဆက်တင်များ",
    admin_title_staff: "📜 ငွေလွှဲမှတ်တမ်းများ (Staff View)",

    // Admin Panel — Tabs
    tab_dashboard: "📊 Dashboard",
    tab_history: "📜 မှတ်တမ်းများ",
    tab_general: "အထွေထွေ",
    tab_banks: "ဘဏ်များ",
    tab_qrs: "QR များ",
    tab_customers: "👥 Customers",
    tab_treasury: "💰 လက်ကျန်ငွေ",
    tab_expenses: "💸 အသုံးစရိတ်",
    tab_logs: "📝 Logs",

    // Admin Panel — Section Headers
    h_dash_volume: "📊 ငွေလွှဲပမာဏ နှင့် အမြတ်ငွေ (Volume & Auto Profit)",
    h_dash_fifo: "📈 FIFO Profit & Active Lots (အမြတ် နှင့် လက်ကျန်)",
    h_history: "📜 ငွေလွှဲမှတ်တမ်းများ",
    h_general_time: "⏱ အချိန်သတ်မှတ်ချက်များ (Main Admin သီးသန့်)",
    h_general_telegram: "🤖 Telegram Bot ချိတ်ဆက်ရန်",
    h_general_daily_report: "📊 Daily Closing Report (နေ့စဉ် အနှစ်ချုပ်)",
    h_general_backup: "💾 Auto Scheduled Backup",
    h_general_api: "🔑 API Keys (Developer Settings)",
    h_general_devices: "📱 စနစ်ထဲဝင်ရောက်ထားသော Device များ",
    h_general_accounts: "🔑 Email / Password ဖြင့် Login ဝင်ခွင့်ရှိသော Account များ",
    h_general_timezone: "⏱ Export တွင်ပြသမည့် နိုင်ငံအချိန်",
    h_general_session: "⏳ Email Login Session Timeout",
    h_general_backup_data: "🚀 System Data Management & Backup",
    h_banks_form: "🏦 ဘဏ်အချက်အလက် ထည့်ရန် / ပြင်ရန်",
    h_banks_list: "📋 ထည့်သွင်းထားသော ဘဏ်များ (ဆွဲရွှေ့ပါ)",
    h_qrs_form: "🔲 QR အသစ် ထည့်ရန် / ပြင်ရန်",
    h_qrs_list: "📋 ထည့်သွင်းထားသော QR များ (ဆွဲရွှေ့ပါ)",
    h_customers_form: "👥 Customer အသစ် ထည့်ရန် / ပြင်ရန်",
    h_customers_list: "📋 Customer စာရင်းများ",
    h_treasury_main: "💰 Master Account လက်ကျန်ငွေများ",
    h_treasury_add: "➕ Master Account အသစ်ထည့်ရန်",
    h_treasury_transfer: "🔄 ဘဏ်အချင်းချင်း ငွေရွှေ့ရန် (Internal Transfer)",
    h_expenses_main: "💸 အထွေထွေ ကုန်ကျစရိတ် မှတ်တမ်း",
    h_expenses_add: "➕ အသုံးစရိတ် အသစ်ထည့်ရန်",
    h_logs_main: "📝 စနစ်အတွင်း လုပ်ဆောင်ချက် မှတ်တမ်းများ",

    // Admin Panel — Common Buttons
    btn_save_new: "Save (အသစ်)",
    btn_update: "Update (ပြင်မည်)",
    btn_duplicate: "Duplicate (ပွားမည်)",
    btn_clear: "ရှင်းမည်",
    btn_refresh: "🔄 Refresh",
    btn_save_generic: "သိမ်းမည်",
    btn_transfer_go: "လွှဲမည်",
    btn_record: "မှတ်တမ်းတင်မည်",
    btn_export: "📥 Export",
    btn_export_transfers: "📥 Export Transfers",
    btn_clear_all: "🗑 Clear All"
  },
  en: {
    app_title: "MMK ↔ THB & VND Exchange Calculator",
    app_sub: "Real-time Currency Converter",
    rate_thb_100k: "THB per 100K MMK",
    rate_thb_sub: "THB for 100,000 Kyats",
    rate_mmk_1thb: "MMK per 1 THB",
    rate_mmk_sub: "Kyats for 1 Baht",
    rate_vnd_1mmk: "VND per 1 MMK",
    rate_vnd_sub: "Dong for 1 Kyat",
    ph_ex1: "e.g., 820",
    ph_ex2: "e.g., 121.95",
    ph_ex3: "e.g., 6.5",
    thb_to_mmk: "THB → MMK",
    mmk_to_thb: "MMK → THB",
    vnd_to_mmk: "VND → MMK",
    mmk_to_vnd: "MMK → VND",
    lbl_thb: "THB Amount",
    lbl_mmk: "MMK Amount",
    lbl_vnd: "VND Amount",
    ph_enter: "Enter amount",
    btn_png: "Save PNG",
    btn_jpg: "Save JPEG",
    btn_share: "📤 Share",
    btn_copy: "📋 Copy Text",
    export_st_title: "Export Settings (PNG/JPEG)",
    export_st_sub: "Choose QR or Bank Info to attach",
    lbl_save_lang: "Export Language",
    lbl_qr_sel: "Select QR",
    lbl_bank_sel: "Select Bank",
    lbl_inc: "Include in Export",
    rad_none: "None (Default)",
    rad_qr: "QR Only",
    rad_bank: "Bank Info Only",
    lbl_cus: "👥 Customer (Optional)",
    btn_quick_add: "➕ Quick Add",
    preview: "Preview",
    owner_name: "Account Name: ",
    bank_preview: "Bank Info Preview",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— Select QR —",
    ph_bank_sel: "— Select Bank —",
    ph_cus_sel: "— None —",

    // Admin Panel — Main Button / Modal Title
    btn_admin_open: "🔒 Admin / Staff",
    admin_title: "⚙️ Admin Settings",
    btn_manual_lot: "➕ Add Manual Lot",
    btn_pdf_report: "📄 PDF Report",
    btn_role_main_admin: "⚙️ Main Admin",
    btn_role_admin: "🛡️ Admin",
    btn_role_staff: "📜 Staff",
    admin_title_main_admin: "⚙️ Main Admin Settings",
    admin_title_staff: "📜 Transfer History (Staff View)",

    // Admin Panel — Tabs
    tab_dashboard: "📊 Dashboard",
    tab_history: "📜 History",
    tab_general: "General",
    tab_banks: "Banks",
    tab_qrs: "QR Codes",
    tab_customers: "👥 Customers",
    tab_treasury: "💰 Treasury",
    tab_expenses: "💸 Expenses",
    tab_logs: "📝 Logs",

    // Admin Panel — Section Headers
    h_dash_volume: "📊 Transfer Volume & Auto Profit",
    h_dash_fifo: "📈 FIFO Profit & Active Lots",
    h_history: "📜 Transfer History",
    h_general_time: "⏱ Time Settings (Main Admin Only)",
    h_general_telegram: "🤖 Connect Telegram Bot",
    h_general_daily_report: "📊 Daily Closing Report",
    h_general_backup: "💾 Auto Scheduled Backup",
    h_general_api: "🔑 API Keys (Developer Settings)",
    h_general_devices: "📱 Devices Logged Into System",
    h_general_accounts: "🔑 Email / Password Login Accounts",
    h_general_timezone: "⏱ Timezone Shown in Export",
    h_general_session: "⏳ Email Login Session Timeout",
    h_general_backup_data: "🚀 System Data Management & Backup",
    h_banks_form: "🏦 Add / Edit Bank Info",
    h_banks_list: "📋 Added Banks (Drag to Reorder)",
    h_qrs_form: "🔲 Add / Edit QR",
    h_qrs_list: "📋 Added QR Codes (Drag to Reorder)",
    h_customers_form: "👥 Add / Edit Customer",
    h_customers_list: "📋 Customer List",
    h_treasury_main: "💰 Master Account Balances",
    h_treasury_add: "➕ Add New Master Account",
    h_treasury_transfer: "🔄 Internal Transfer Between Accounts",
    h_expenses_main: "💸 General Expense Records",
    h_expenses_add: "➕ Add New Expense",
    h_logs_main: "📝 System Activity Logs",

    // Admin Panel — Common Buttons
    btn_save_new: "Save (New)",
    btn_update: "Update (Edit)",
    btn_duplicate: "Duplicate (Copy)",
    btn_clear: "Clear",
    btn_refresh: "🔄 Refresh",
    btn_save_generic: "Save",
    btn_transfer_go: "Transfer",
    btn_record: "Record",
    btn_export: "📥 Export",
    btn_export_transfers: "📥 Export Transfers",
    btn_clear_all: "🗑 Clear All"
  },
  th: {
    app_title: "เครื่องคิดเลขแลกเปลี่ยน MMK ↔ THB & VND",
    app_sub: "คำนวณอัตราแลกเปลี่ยนเรียลไทม์",
    rate_thb_100k: "บาท ต่อ 100,000 จ๊าด",
    rate_thb_sub: "THB ต่อ 100,000 MMK",
    rate_mmk_1thb: "จ๊าด ต่อ 1 บาท",
    rate_mmk_sub: "MMK ต่อ 1 THB",
    rate_vnd_1mmk: "ดอง ต่อ 1 จ๊าด",
    rate_vnd_sub: "VND ต่อ 1 MMK",
    ph_ex1: "เช่น 820",
    ph_ex2: "เช่น 121.95",
    ph_ex3: "เช่น 6.5",
    thb_to_mmk: "บาท → จ๊าด",
    mmk_to_thb: "จ๊าด → บาท",
    vnd_to_mmk: "ดอง → จ๊าด",
    mmk_to_vnd: "จ๊าด → ดอง",
    lbl_thb: "จำนวนเงิน (THB)",
    lbl_mmk: "จำนวนเงิน (MMK)",
    lbl_vnd: "จำนวนเงิน (VND)",
    ph_enter: "กรอกจำนวนเงิน",
    btn_png: "บันทึก PNG",
    btn_jpg: "บันทึก JPEG",
    btn_share: "📤 แชร์",
    btn_copy: "📋 คัดลอก",
    export_st_title: "ตั้งค่าการส่งออกรูปภาพ",
    export_st_sub: "เลือก QR หรือ ข้อมูลธนาคาร",
    lbl_save_lang: "ภาษาของรูปภาพ",
    lbl_qr_sel: "เลือก QR",
    lbl_bank_sel: "เลือกธนาคาร",
    lbl_inc: "สิ่งที่จะรวมในรูป",
    rad_none: "ไม่มี (ค่าเริ่มต้น)",
    rad_qr: "เฉพาะ QR",
    rad_bank: "เฉพาะข้อมูลธนาคาร",
    lbl_cus: "👥 ลูกค้า (ไม่บังคับ)",
    btn_quick_add: "➕ เพิ่มด่วน",
    preview: "ตัวอย่าง",
    owner_name: "ชื่อบัญชี: ",
    bank_preview: "ตัวอย่างข้อมูลธนาคาร",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— เลือก QR —",
    ph_bank_sel: "— เลือกธนาคาร —",
    ph_cus_sel: "— ไม่ระบุ —",

    // Admin Panel — Main Button / Modal Title
    btn_admin_open: "🔒 แอดมิน / พนักงาน",
    admin_title: "⚙️ ตั้งค่าผู้ดูแลระบบ",
    btn_manual_lot: "➕ เพิ่ม Lot ด้วยตนเอง",
    btn_pdf_report: "📄 รายงาน PDF",
    btn_role_main_admin: "⚙️ Main Admin",
    btn_role_admin: "🛡️ แอดมิน",
    btn_role_staff: "📜 พนักงาน",
    admin_title_main_admin: "⚙️ ตั้งค่า Main Admin",
    admin_title_staff: "📜 ประวัติการโอนเงิน (มุมมองพนักงาน)",

    // Admin Panel — Tabs
    tab_dashboard: "📊 แดชบอร์ด",
    tab_history: "📜 ประวัติ",
    tab_general: "ทั่วไป",
    tab_banks: "ธนาคาร",
    tab_qrs: "คิวอาร์โค้ด",
    tab_customers: "👥 ลูกค้า",
    tab_treasury: "💰 คลังเงิน",
    tab_expenses: "💸 ค่าใช้จ่าย",
    tab_logs: "📝 บันทึก",

    // Admin Panel — Section Headers
    h_dash_volume: "📊 ปริมาณการโอนและกำไรอัตโนมัติ",
    h_dash_fifo: "📈 กำไร FIFO และล็อตที่ใช้งานอยู่",
    h_history: "📜 ประวัติการโอนเงิน",
    h_general_time: "⏱ การตั้งค่าเวลา (เฉพาะ Main Admin)",
    h_general_telegram: "🤖 เชื่อมต่อ Telegram Bot",
    h_general_daily_report: "📊 รายงานสรุปประจำวัน",
    h_general_backup: "💾 สำรองข้อมูลอัตโนมัติ",
    h_general_api: "🔑 API Keys (การตั้งค่านักพัฒนา)",
    h_general_devices: "📱 อุปกรณ์ที่เข้าสู่ระบบ",
    h_general_accounts: "🔑 บัญชีที่เข้าสู่ระบบด้วย Email / รหัสผ่าน",
    h_general_timezone: "⏱ เขตเวลาที่แสดงในไฟล์ส่งออก",
    h_general_session: "⏳ หมดเวลาเซสชันการเข้าสู่ระบบ",
    h_general_backup_data: "🚀 การจัดการและสำรองข้อมูลระบบ",
    h_banks_form: "🏦 เพิ่ม / แก้ไขข้อมูลธนาคาร",
    h_banks_list: "📋 ธนาคารที่เพิ่มแล้ว (ลากเพื่อจัดเรียง)",
    h_qrs_form: "🔲 เพิ่ม / แก้ไข QR",
    h_qrs_list: "📋 QR ที่เพิ่มแล้ว (ลากเพื่อจัดเรียง)",
    h_customers_form: "👥 เพิ่ม / แก้ไขลูกค้า",
    h_customers_list: "📋 รายชื่อลูกค้า",
    h_treasury_main: "💰 ยอดคงเหลือบัญชีหลัก",
    h_treasury_add: "➕ เพิ่มบัญชีหลักใหม่",
    h_treasury_transfer: "🔄 โอนเงินภายในระหว่างบัญชี",
    h_expenses_main: "💸 บันทึกค่าใช้จ่ายทั่วไป",
    h_expenses_add: "➕ เพิ่มค่าใช้จ่ายใหม่",
    h_logs_main: "📝 บันทึกกิจกรรมระบบ",

    // Admin Panel — Common Buttons
    btn_save_new: "บันทึก (ใหม่)",
    btn_update: "อัปเดต (แก้ไข)",
    btn_duplicate: "ทำสำเนา (คัดลอก)",
    btn_clear: "ล้าง",
    btn_refresh: "🔄 รีเฟรช",
    btn_save_generic: "บันทึก",
    btn_transfer_go: "โอน",
    btn_record: "บันทึกรายการ",
    btn_export: "📥 ส่งออก",
    btn_export_transfers: "📥 ส่งออกรายการโอน",
    btn_clear_all: "🗑 ล้างทั้งหมด"
  },
  vi: {
    app_title: "Máy tính tỷ giá MMK ↔ THB & VND",
    app_sub: "Công cụ chuyển đổi tiền tệ",
    rate_thb_100k: "THB mỗi 100K MMK",
    rate_thb_sub: "THB cho 100,000 Kyats",
    rate_mmk_1thb: "MMK mỗi 1 THB",
    rate_mmk_sub: "Kyats cho 1 Baht",
    rate_vnd_1mmk: "VND mỗi 1 MMK",
    rate_vnd_sub: "Đồng cho 1 Kyat",
    ph_ex1: "VD - 820",
    ph_ex2: "VD - 121.95",
    ph_ex3: "VD - 6.5",
    thb_to_mmk: "THB → MMK",
    mmk_to_thb: "MMK → THB",
    vnd_to_mmk: "VND → MMK",
    mmk_to_vnd: "MMK → VND",
    lbl_thb: "Số tiền (THB)",
    lbl_mmk: "Số tiền (MMK)",
    lbl_vnd: "Số tiền (VND)",
    ph_enter: "Nhập số tiền",
    btn_png: "Lưu PNG",
    btn_jpg: "Lưu JPEG",
    btn_share: "📤 Chia sẻ",
    btn_copy: "📋 Sao chép",
    export_st_title: "Cài đặt hình ảnh",
    export_st_sub: "Chọn QR hoặc Ngân hàng",
    lbl_save_lang: "Ngôn ngữ Ảnh",
    lbl_qr_sel: "Chọn QR",
    lbl_bank_sel: "Chọn Ngân hàng",
    lbl_inc: "Bao gồm trong ảnh",
    rad_none: "Không (Mặc định)",
    rad_qr: "Chỉ QR",
    rad_bank: "Chỉ Ngân hàng",
    lbl_cus: "👥 Khách hàng (Tùy chọn)",
    btn_quick_add: "➕ Thêm nhanh",
    preview: "Bản xem trước",
    owner_name: "Tên tài khoản: ",
    bank_preview: "Ngân hàng xem trước",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— Chọn QR —",
    ph_bank_sel: "— Chọn Ngân hàng —",
    ph_cus_sel: "— Trống —",

    // Admin Panel — Main Button / Modal Title
    btn_admin_open: "🔒 Quản trị / Nhân viên",
    admin_title: "⚙️ Cài đặt Quản trị",
    btn_manual_lot: "➕ Thêm Lô thủ công",
    btn_pdf_report: "📄 Báo cáo PDF",
    btn_role_main_admin: "⚙️ Main Admin",
    btn_role_admin: "🛡️ Quản trị viên",
    btn_role_staff: "📜 Nhân viên",
    admin_title_main_admin: "⚙️ Cài đặt Main Admin",
    admin_title_staff: "📜 Lịch sử chuyển tiền (Chế độ Nhân viên)",

    // Admin Panel — Tabs
    tab_dashboard: "📊 Bảng điều khiển",
    tab_history: "📜 Lịch sử",
    tab_general: "Chung",
    tab_banks: "Ngân hàng",
    tab_qrs: "Mã QR",
    tab_customers: "👥 Khách hàng",
    tab_treasury: "💰 Ngân quỹ",
    tab_expenses: "💸 Chi phí",
    tab_logs: "📝 Nhật ký",

    // Admin Panel — Section Headers
    h_dash_volume: "📊 Khối lượng chuyển & Lợi nhuận tự động",
    h_dash_fifo: "📈 Lợi nhuận FIFO & Lô đang hoạt động",
    h_history: "📜 Lịch sử chuyển tiền",
    h_general_time: "⏱ Cài đặt thời gian (Chỉ Main Admin)",
    h_general_telegram: "🤖 Kết nối Telegram Bot",
    h_general_daily_report: "📊 Báo cáo tổng kết hằng ngày",
    h_general_backup: "💾 Sao lưu tự động theo lịch",
    h_general_api: "🔑 API Keys (Cài đặt nhà phát triển)",
    h_general_devices: "📱 Thiết bị đã đăng nhập hệ thống",
    h_general_accounts: "🔑 Tài khoản đăng nhập bằng Email / Mật khẩu",
    h_general_timezone: "⏱ Múi giờ hiển thị khi xuất",
    h_general_session: "⏳ Hết hạn phiên đăng nhập Email",
    h_general_backup_data: "🚀 Quản lý & sao lưu dữ liệu hệ thống",
    h_banks_form: "🏦 Thêm / Sửa thông tin ngân hàng",
    h_banks_list: "📋 Ngân hàng đã thêm (Kéo để sắp xếp)",
    h_qrs_form: "🔲 Thêm / Sửa QR",
    h_qrs_list: "📋 Mã QR đã thêm (Kéo để sắp xếp)",
    h_customers_form: "👥 Thêm / Sửa khách hàng",
    h_customers_list: "📋 Danh sách khách hàng",
    h_treasury_main: "💰 Số dư tài khoản chính",
    h_treasury_add: "➕ Thêm tài khoản chính mới",
    h_treasury_transfer: "🔄 Chuyển tiền nội bộ giữa các tài khoản",
    h_expenses_main: "💸 Ghi chép chi phí chung",
    h_expenses_add: "➕ Thêm chi phí mới",
    h_logs_main: "📝 Nhật ký hoạt động hệ thống",

    // Admin Panel — Common Buttons
    btn_save_new: "Lưu (Mới)",
    btn_update: "Cập nhật (Sửa)",
    btn_duplicate: "Nhân bản (Sao chép)",
    btn_clear: "Xóa",
    btn_refresh: "🔄 Làm mới",
    btn_save_generic: "Lưu",
    btn_transfer_go: "Chuyển",
    btn_record: "Ghi lại",
    btn_export: "📥 Xuất",
    btn_export_transfers: "📥 Xuất dữ liệu chuyển khoản",
    btn_clear_all: "🗑 Xóa tất cả"
  }
};

// ပြေစာ (Export) ထုတ်ရာတွင် အသုံးပြုမည့် စာသားများ
const I18N = {
  en: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"THB → MMK", h_mmk2thb:"MMK → THB", h_vnd2mmk:"VND → MMK", h_mmk2vnd:"MMK → VND", sub_thb2mmk:"Thai Baht to Myanmar Kyat", sub_mmk2thb:"Myanmar Kyat to Thai Baht", sub_vnd2mmk:"Vietnamese Dong to Myanmar Kyat", sub_mmk2vnd:"Myanmar Kyat to Vietnamese Dong", lbl_thb:"Amount (THB)", lbl_mmk:"Amount (MMK)", lbl_vnd:"Amount (VND)", in_thb:"Input THB", in_mmk:"Input MMK", in_vnd:"Input VND", out_mmk:"Result MMK", out_thb:"Result THB", out_vnd:"Result VND", bankTitle:"Transfer Bank Information", bankLabel:"Bank Information", accName:"Account Name", accNo:"Account Number", qrTitle:"Bank QR / Payment", owner:"Account Name", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" },
  th: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"บาท → จ๊าด", h_mmk2thb:"จ๊าด → บาท", h_vnd2mmk:"ดอง → จ๊าด", h_mmk2vnd:"จ๊าด → ดอง", sub_thb2mmk:"แปลงเงินบาทไทยเป็นจ๊าดเมียนมา", sub_mmk2thb:"แปลงจ๊าดเมียนมาเป็นเงินบาทไทย", sub_vnd2mmk:"แปลงเงินดองเวียดนามเป็นจ๊าดเมียนมา", sub_mmk2vnd:"แปลงจ๊าดเมียนมาเป็นเงินดองเวียดนาม", lbl_thb:"จำนวนเงิน (THB)", lbl_mmk:"จำนวนเงิน (MMK)", lbl_vnd:"จำนวนเงิน (VND)", in_thb:"กรอกจำนวนบาท", in_mmk:"กรอกจำนวนจ๊าด", in_vnd:"กรอกจำนวนดอง", out_mmk:"ผลลัพธ์ (MMK)", out_thb:"ผลลัพธ์ (THB)", out_vnd:"ผลลัพธ์ (VND)", bankTitle:"ข้อมูลบัญชีสำหรับโอน", bankLabel:"ข้อมูลบัญชีธนาคาร", accName:"ชื่อบัญชี", accNo:"เลขบัญชี", qrTitle:"คิวอาร์ธนาคาร", owner:"ชื่อบัญชี", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" },
  vi: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"THB → MMK", h_mmk2thb:"MMK → THB", h_vnd2mmk:"VND → MMK", h_mmk2vnd:"MMK → VND", sub_thb2mmk:"Đổi THB sang MMK", sub_mmk2thb:"Đổi MMK sang THB", sub_vnd2mmk:"Đổi VND sang MMK", sub_mmk2vnd:"Đổi MMK sang VND", lbl_thb:"Số tiền (THB)", lbl_mmk:"Số tiền (MMK)", lbl_vnd:"Số tiền (VND)", in_thb:"Nhập THB", in_mmk:"Nhập MMK", in_vnd:"Nhập VND", out_mmk:"Kết quả MMK", out_thb:"Kết quả THB", out_vnd:"Kết quả VND", bankTitle:"Thông tin chuyển khoản", bankLabel:"Thông tin ngân hàng", accName:"Tên tài khoản", accNo:"Số tài khoản", qrTitle:"QR Ngân hàng", owner:"Tên tài khoản", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" }
};
