// UI တွင်ပြသမည့် စာသားများ (System Dictionary)
const SYS_DICT = {
  my: {
    app_title: "MMK ↔ THB & VND ငွေလဲတွက်ချက်ခြင်း",
    app_sub: "MMK ↔ THB & VND Exchange Calculator",
    rate_thb_100k: "၁ သိန်း အတွက် ဘတ် (THB)",
    rate_thb_sub: "THB per 100,000 MMK",
    rate_mmk_1thb: "၁ ဘတ် အတွက် ကျပ် (MMK)",
    rate_mmk_sub: "MMK per 1 THB",
    rate_vnd_1mmk: "၁ ကျပ် အတွက် ဒေါင် (VND)",
    rate_vnd_sub: "VND per 1 MMK",
    ph_ex1: "ဥပမာ - 820",
    ph_ex2: "ဥပမာ - 121.95",
    ph_ex3: "ဥပမာ - 6.5",
    thb_to_mmk: "ဘတ် → မြန်မာကျပ်",
    mmk_to_thb: "မြန်မာကျပ် → ဘတ်",
    vnd_to_mmk: "ဗီယက်နမ်ဒေါင် → မြန်မာကျပ်",
    mmk_to_vnd: "မြန်မာကျပ် → ဗီယက်နမ်ဒေါင်",
    lbl_thb: "ဘတ်ငွေ",
    lbl_mmk: "မြန်မာကျပ်",
    lbl_vnd: "ဒေါင်ငွေ",
    ph_enter: "ရိုက်ထည့်ပါ",
    btn_png: "Save PNG",
    btn_jpg: "Save JPEG",
    btn_share: "📤 Share",
    btn_copy: "📋 Copy Text",
    export_st_title: "Save PNG/JPEG + Bank QR",
    export_st_sub: "QR / Bank Info / မပါ — တစ်ခုတည်းပဲရွေးနိုင်",
    lbl_save_lang: "Save Export Language",
    lbl_qr_sel: "QR Select",
    lbl_bank_sel: "Bank Select",
    lbl_inc: "Export ထဲ ဘာထည့်မလဲ",
    rad_none: "မပါ (Default)",
    rad_qr: "QR ပဲပါ",
    rad_bank: "Bank Info ပဲပါ",
    lbl_cus: "👥 Customer (မရွေးပါက ပြေစာတွင်မပါပါ)",
    btn_quick_add: "➕ အမြန်ထည့်မည်",
    preview: "Preview",
    owner_name: "အကောင့်နာမည်: ",
    bank_preview: "Bank Info Preview",
    
    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— QR ရွေးပါ —",
    ph_bank_sel: "— ဘဏ်ရွေးပါ —",
    ph_cus_sel: "— မထည့်ပါ —"
  },
  en: {
    app_title: "MMK ↔ THB & VND Exchange Calculator",
    app_sub: "Real-time Currency Converter",
    rate_thb_100k: "THB per 100K MMK",
    rate_thb_sub: "THB for 100,000 Kyats",
    rate_mmk_1thb: "MMK per 1 THB",
    rate_mmk_sub: "Kyats for 1 Baht",
    rate_vnd_1mmk: "VND per 1 MMK",
    rate_vnd_sub: "Dong for 1 Kyat",
    ph_ex1: "e.g., 820",
    ph_ex2: "e.g., 121.95",
    ph_ex3: "e.g., 6.5",
    thb_to_mmk: "THB → MMK",
    mmk_to_thb: "MMK → THB",
    vnd_to_mmk: "VND → MMK",
    mmk_to_vnd: "MMK → VND",
    lbl_thb: "THB Amount",
    lbl_mmk: "MMK Amount",
    lbl_vnd: "VND Amount",
    ph_enter: "Enter amount",
    btn_png: "Save PNG",
    btn_jpg: "Save JPEG",
    btn_share: "📤 Share",
    btn_copy: "📋 Copy Text",
    export_st_title: "Export Settings (PNG/JPEG)",
    export_st_sub: "Choose QR or Bank Info to attach",
    lbl_save_lang: "Export Language",
    lbl_qr_sel: "Select QR",
    lbl_bank_sel: "Select Bank",
    lbl_inc: "Include in Export",
    rad_none: "None (Default)",
    rad_qr: "QR Only",
    rad_bank: "Bank Info Only",
    lbl_cus: "👥 Customer (Optional)",
    btn_quick_add: "➕ Quick Add",
    preview: "Preview",
    owner_name: "Account Name: ",
    bank_preview: "Bank Info Preview",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— Select QR —",
    ph_bank_sel: "— Select Bank —",
    ph_cus_sel: "— None —"
  },
  th: {
    app_title: "เครื่องคิดเลขแลกเปลี่ยน MMK ↔ THB & VND",
    app_sub: "คำนวณอัตราแลกเปลี่ยนเรียลไทม์",
    rate_thb_100k: "บาท ต่อ 100,000 จ๊าด",
    rate_thb_sub: "THB ต่อ 100,000 MMK",
    rate_mmk_1thb: "จ๊าด ต่อ 1 บาท",
    rate_mmk_sub: "MMK ต่อ 1 THB",
    rate_vnd_1mmk: "ดอง ต่อ 1 จ๊าด",
    rate_vnd_sub: "VND ต่อ 1 MMK",
    ph_ex1: "เช่น 820",
    ph_ex2: "เช่น 121.95",
    ph_ex3: "เช่น 6.5",
    thb_to_mmk: "บาท → จ๊าด",
    mmk_to_thb: "จ๊าด → บาท",
    vnd_to_mmk: "ดอง → จ๊าด",
    mmk_to_vnd: "จ๊าด → ดอง",
    lbl_thb: "จำนวนเงิน (THB)",
    lbl_mmk: "จำนวนเงิน (MMK)",
    lbl_vnd: "จำนวนเงิน (VND)",
    ph_enter: "กรอกจำนวนเงิน",
    btn_png: "บันทึก PNG",
    btn_jpg: "บันทึก JPEG",
    btn_share: "📤 แชร์",
    btn_copy: "📋 คัดลอก",
    export_st_title: "ตั้งค่าการส่งออกรูปภาพ",
    export_st_sub: "เลือก QR หรือ ข้อมูลธนาคาร",
    lbl_save_lang: "ภาษาของรูปภาพ",
    lbl_qr_sel: "เลือก QR",
    lbl_bank_sel: "เลือกธนาคาร",
    lbl_inc: "สิ่งที่จะรวมในรูป",
    rad_none: "ไม่มี (ค่าเริ่มต้น)",
    rad_qr: "เฉพาะ QR",
    rad_bank: "เฉพาะข้อมูลธนาคาร",
    lbl_cus: "👥 ลูกค้า (ไม่บังคับ)",
    btn_quick_add: "➕ เพิ่มด่วน",
    preview: "ตัวอย่าง",
    owner_name: "ชื่อบัญชี: ",
    bank_preview: "ตัวอย่างข้อมูลธนาคาร",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— เลือก QR —",
    ph_bank_sel: "— เลือกธนาคาร —",
    ph_cus_sel: "— ไม่ระบุ —"
  },
  vi: {
    app_title: "Máy tính tỷ giá MMK ↔ THB & VND",
    app_sub: "Công cụ chuyển đổi tiền tệ",
    rate_thb_100k: "THB mỗi 100K MMK",
    rate_thb_sub: "THB cho 100,000 Kyats",
    rate_mmk_1thb: "MMK mỗi 1 THB",
    rate_mmk_sub: "Kyats cho 1 Baht",
    rate_vnd_1mmk: "VND mỗi 1 MMK",
    rate_vnd_sub: "Đồng cho 1 Kyat",
    ph_ex1: "VD - 820",
    ph_ex2: "VD - 121.95",
    ph_ex3: "VD - 6.5",
    thb_to_mmk: "THB → MMK",
    mmk_to_thb: "MMK → THB",
    vnd_to_mmk: "VND → MMK",
    mmk_to_vnd: "MMK → VND",
    lbl_thb: "Số tiền (THB)",
    lbl_mmk: "Số tiền (MMK)",
    lbl_vnd: "Số tiền (VND)",
    ph_enter: "Nhập số tiền",
    btn_png: "Lưu PNG",
    btn_jpg: "Lưu JPEG",
    btn_share: "📤 Chia sẻ",
    btn_copy: "📋 Sao chép",
    export_st_title: "Cài đặt hình ảnh",
    export_st_sub: "Chọn QR hoặc Ngân hàng",
    lbl_save_lang: "Ngôn ngữ Ảnh",
    lbl_qr_sel: "Chọn QR",
    lbl_bank_sel: "Chọn Ngân hàng",
    lbl_inc: "Bao gồm trong ảnh",
    rad_none: "Không (Mặc định)",
    rad_qr: "Chỉ QR",
    rad_bank: "Chỉ Ngân hàng",
    lbl_cus: "👥 Khách hàng (Tùy chọn)",
    btn_quick_add: "➕ Thêm nhanh",
    preview: "Bản xem trước",
    owner_name: "Tên tài khoản: ",
    bank_preview: "Ngân hàng xem trước",

    // Dropdown အတွက် စာသားများ
    ph_qr_sel: "— Chọn QR —",
    ph_bank_sel: "— Chọn Ngân hàng —",
    ph_cus_sel: "— Trống —"
  }
};

// ပြေစာ (Export) ထုတ်ရာတွင် အသုံးပြုမည့် စာသားများ
const I18N = {
  en: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"THB → MMK", h_mmk2thb:"MMK → THB", h_vnd2mmk:"VND → MMK", h_mmk2vnd:"MMK → VND", sub_thb2mmk:"Thai Baht to Myanmar Kyat", sub_mmk2thb:"Myanmar Kyat to Thai Baht", sub_vnd2mmk:"Vietnamese Dong to Myanmar Kyat", sub_mmk2vnd:"Myanmar Kyat to Vietnamese Dong", lbl_thb:"Amount (THB)", lbl_mmk:"Amount (MMK)", lbl_vnd:"Amount (VND)", in_thb:"Input THB", in_mmk:"Input MMK", in_vnd:"Input VND", out_mmk:"Result MMK", out_thb:"Result THB", out_vnd:"Result VND", bankTitle:"Transfer Bank Information", bankLabel:"Bank Information", accName:"Account Name", accNo:"Account Number", qrTitle:"Bank QR / Payment", owner:"Account Name", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" },
  th: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"บาท → จ๊าด", h_mmk2thb:"จ๊าด → บาท", h_vnd2mmk:"ดอง → จ๊าด", h_mmk2vnd:"จ๊าด → ดอง", sub_thb2mmk:"แปลงเงินบาทไทยเป็นจ๊าดเมียนมา", sub_mmk2thb:"แปลงจ๊าดเมียนมาเป็นเงินบาทไทย", sub_vnd2mmk:"แปลงเงินดองเวียดนามเป็นจ๊าดเมียนมา", sub_mmk2vnd:"แปลงจ๊าดเมียนมาเป็นเงินดองเวียดนาม", lbl_thb:"จำนวนเงิน (THB)", lbl_mmk:"จำนวนเงิน (MMK)", lbl_vnd:"จำนวนเงิน (VND)", in_thb:"กรอกจำนวนบาท", in_mmk:"กรอกจำนวนจ๊าด", in_vnd:"กรอกจำนวนดอง", out_mmk:"ผลลัพธ์ (MMK)", out_thb:"ผลลัพธ์ (THB)", out_vnd:"ผลลัพธ์ (VND)", bankTitle:"ข้อมูลบัญชีสำหรับโอน", bankLabel:"ข้อมูลบัญชีธนาคาร", accName:"ชื่อบัญชี", accNo:"เลขบัญชี", qrTitle:"คิวอาร์ธนาคาร", owner:"ชื่อบัญชี", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" },
  vi: { titleTop: "Thailand Guide - Supplier By Ye", h_thb2mmk:"THB → MMK", h_mmk2thb:"MMK → THB", h_vnd2mmk:"VND → MMK", h_mmk2vnd:"MMK → VND", sub_thb2mmk:"Đổi THB sang MMK", sub_mmk2thb:"Đổi MMK sang THB", sub_vnd2mmk:"Đổi VND sang MMK", sub_mmk2vnd:"Đổi MMK sang VND", lbl_thb:"Số tiền (THB)", lbl_mmk:"Số tiền (MMK)", lbl_vnd:"Số tiền (VND)", in_thb:"Nhập THB", in_mmk:"Nhập MMK", in_vnd:"Nhập VND", out_mmk:"Kết quả MMK", out_thb:"Kết quả THB", out_vnd:"Kết quả VND", bankTitle:"Thông tin chuyển khoản", bankLabel:"Thông tin ngân hàng", accName:"Tên tài khoản", accNo:"Số tài khoản", qrTitle:"QR Ngân hàng", owner:"Tên tài khoản", rateTpl:"100,000 MMK = {r} THB | 1 THB = {inv} MMK", rateVndTpl:"1 MMK = {v} VND" }
};
